example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('wishlist/', include('wishlist.urls')),
]

wishlist/urls.py
from django.urls import path
from wishlist.views import *

app_name = 'wishlist'

urlpatterns = [
    path('', show_wishlist, name='show_wishlist'),
    path('xml/', show_xml, name='show_xml'), #customize the name of the function 
    path('json/', show_json, name='show_json'), #customise the name of the function created
    path('html/', show_wishlist, name='show_wishlist'),
    path('json/<int:id>', show_json_by_id, name='show_json_by_id'),
    path('xml/<int:id>', show_xml_by_id, name='show_xml_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    #Ajax
    path('ajax/', show_ajax, name='show_ajax'),
    path('create_data/', add_wishlist_item, name='add_wishlist_item')
]

example_app/models.py
from django.db import models

# Create your models here.

wishlist/models.py
from django.db import models

# Create your models here.
class ItemWishlist(models.Model):
    item_name = models.CharField(max_length=50)
    item_price = models.IntegerField()
    description = models.TextField()

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

wishlist/views.py
from ast import Param
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.http import HttpResponse, HttpResponseNotFound
from django.core import serializers
from django.shortcuts import render
from wishlist.models import ItemWishlist
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required


# Create your views here.
@login_required(login_url='/wishlist/login/')
def show_wishlist(request):
    data_wishlist_item = ItemWishlist.objects.all()
    context = {
    'list_item': data_wishlist_item,
    'name': 'Dhiwa Arya Kusumah',
    'npm': '2106657115',
    'last_login': request.COOKIES['last_login'],
    }
    return render(request, "wishlist.html", context)

def show_ajax(request):
    context = {
        'name': 'Dhiwa Arya Kusumah',
        'npm': '2106657115',
        'last_login': request.COOKIES['last_login'],
    }
    return render(request, "wishlist_ajax.html", context)

def show_xml(request):
    data = ItemWishlist.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = ItemWishlist.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_json_by_id(request, id):
    data = ItemWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = ItemWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Account successfully created!')
            return redirect('wishlist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # login first
            response = HttpResponseRedirect(reverse("wishlist:show_wishlist")) # create response
            response.set_cookie('last_login', str(datetime.datetime.now())) # create last_login cookie and add it to response
            return response
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('wishlist:login'))
    response.delete_cookie('last_login')
    return response


#---------------------------------------------------AJAX Implementation-------------------------------------------------------------#
def add_wishlist_item(request):
    if request.method == 'POST':
        nama_barang = request.POST.get("item_name")
        harga_barang = request.POST.get("item_price")
        deskripsi = request.POST.get("description")

        new_barang = ItemWishlist(nama_barang=nama_barang, harga_barang=harga_barang, deskripsi=deskripsi)
        new_barang.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"></script>
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>

</html>

wishlist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<div class = "login">

    <h1>Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn login_btn" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    Don't have an account? <a href="{% url 'wishlist:register' %}">Create Account</a>

</div>

{% endblock content %}

wishlist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Account Registration</title>
{% endblock meta %}

{% block content %}  

<div class = "login">
    
    <h1>Registration Form</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Register"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

wishlist/templates/wishlist.html
{% extends 'base.html' %}
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"></script>
{% block content %}

<!--CSS Design-->
<style>
    body {
      font-family: sans-serif;
      background-color:#f7c97e

    }
  
    table {
      /* border-collapse: collapse; */
      box-shadow: 0 5px 10px gray;  
      background-color:#d8d8d8;
      text-align: left;
      overflow: hidden;
      padding: 0 20px;
      justify-content: center;
      align-items: center;
    }
  
    thead {
      box-shadow: 0 5px 10px gray;
      background-color: #D9D4D1;
    }
  
    th {
      padding: 1rem 2rem;
      text-transform: uppercase;
      letter-spacing: 0.1rem;
      font-size: 0.7rem;
      font-weight: 900;
    }
  
    td {
      padding: 1rem 2rem;
    }
  
    h1,h5 {
        font-family: sans-serif;
        text-align: center;
        color:white;
        font-size: 25px;
        font-weight: 600;
      }

    p{
        font-family: sans-serif;
        text-align: center;
        color:white;
        font-size: 20px;
    }
  
    h3{
      text-align: center;
      color: #57be5d;
    }
  
    h4{
      text-align: center;
      color: #eb1e39;
    }


    .buttons {
		display: flex;
        justify-content: center;
        padding: 20px 32px ;
	}

    a {
			padding: 15px 20px;
			font: 13px ;
			font-weight: 700;
			letter-spacing: 2px;
			text-transform: uppercase;
			text-decoration: none;
			text-align: center;
			margin: 1em;
		}

    a:hover {
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.20), 0 6px 20px 0 rgba(0, 0, 0, 0.20);
    }

        .button1 {
	color: white;
	background-color: red;
	border: 5px solid transparent;
	transition: .2s ease;
	border-radius: 50px;
    padding-right:  30px;
}

.button1:hover {
	color: blue;
	background-color: black;
	transform: scale(1.1);
	border: 5px white;
}

* {
	box-sizing: border-box;
}

body {
	font-family: 'Montserrat', sans-serif;
	line-height: 1.6;
	margin: 0;
	min-height: 100vh;
}
ul {
  margin-top: 0px;
  margin-bottom: 0px;
  padding: 0px;
  list-style: none;
}

a {
	text-decoration: none;
}



.logo {
	margin: 0;
	font-size: 1.45em;
}

.main-nav {
	margin-top: 5px;

}
.logo a,
.main-nav a {
	padding: 10px 15px;
	text-transform: uppercase;
	text-align: center;
	display: block;
}

.main-nav a {
	color: #34495e;
	font-size: .99em;
}

.main-nav a:hover {
	color: #718daa;
}

.header {
	padding-top: .5em;
	padding-bottom: .5em;
	/* border: 1px solid #a2a2a2; */
	background-color: #a87b32;
	-webkit-box-shadow: 0px 0px 14px 0px rgba(0,0,0,0.75);
	-moz-box-shadow: 0px 0px 14px 0px rgba(0,0,0,0.75);
	box-shadow: 0px 0px 14px 0px rgba(0,0,0,0.75);
	-webkit-border-radius: 5px;
	-moz-border-radius: 5px;
	border-radius: 5px;
}

.header,
	.main-nav {
		display: flex;
	}
	.header {
		flex-direction: column;
		align-items: center;
		width: 100%;
		margin: 0 auto;
		max-width: 20000px;
	}
  </style>

<!--HTML content-->
<body>
    <header class="header">
      <ul class="main-nav">
          <li><a>Dhiwa</a></li>
          <li><a href="{% url 'wishlist:show_ajax' %}">wishlist</a></li>
          <li><a href="{% url 'wishlist:login' %}">Login</a></li>
          <li><a href="{% url 'wishlist:register' %}">Register</a></li>
      </ul>
	</header> 
          </div>
        </div>
      </nav>
<br>
<h5>Name: </h5>
<p>{{name}}</p>
<h5>Student ID:</h5>
<p>{{npm}}</p>

<table style="margin-left:auto;margin-right:auto;">
    <tr>
    <thead>
        <th>Item Name</th>
        <th>Item Price</th>
        <th>Description</th>
    </thead>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for item in list_item %}
    <tr>
        <tbody>
            <th>{{item.item_name}}</th>
            <th>{{item.item_price}}</th>
            <th>{{item.description}}</th>
        </tbody>
    </tr>
{% endfor %}
</table>
<br>

<h5>Last Login: {{ last_login }}</h5>
<div class="container">
	<div class="buttons" >
		<a href="{% url 'wishlist:logout' %}" class="button1" target="_blank" rel="noopener">Logout</a>
    </body>
    </div>
</div>

<!-- <button><a href="{% url 'wishlist:logout' %}">Logout</a></button> -->

{% endblock content %}

wishlist/templates/wishlist_ajax.html
{% extends 'base.html' %}
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"></script>
{% block content %}
<style>
    body {
      font-family: sans-serif;
      color: #07BEB8;
      background-color: linear-gradient(#9CEAEF,#c4fff9);
    }

    h1 {
      font-weight: bold;
      display: flex;
      justify-content: center;
      margin: 20px;
    }

    form {
      display: flex;
      justify-content: center;
      margin: 20px;
    }

    button {
      margin: 10px
    }

    table {
      /* border-collapse: collapse; */
      box-shadow: 0 5px 10px gray;  
      background-color:#d8d8d8;
      text-align: left;
      overflow: hidden;
      padding: 0 20px;
      display: flex;
      justify-content: center;
      align-items: center;
      letter-spacing: 0.1rem;
    }
</style>


<h1>Wishlist</h1>
  <form id="form" onsubmit="return false;">
    {% csrf_token %}
    <label>Item name</label>
    <input type="text" name="nama_barang"></input>
    <label>Item Price</label>
    <input type="number" name="harga_barang"></input>
    <label>Description</label>
    <input type="text" name="deskripsi"></input>
    <button id="button" type="submit"  value="Submit"></button>
  </form>

  <table id="table"></table>

<script>
  async function getWishlist() {
    return fetch("{% url 'wishlist:show_json' %}").then((res) => res.json())
  }

  async function refreshWishlist() {
        document.getElementById("table").innerHTML = ""
        const wishlist = await getWishlist()
        let htmlString = `<tr>
          <th>Item name</th>
          <th>Item price</th>
          <th>Description</th>
        </tr>`
        wishlist.forEach((item) => {
          htmlString += `\n<tr>
          <th>${item.fields.item_name}</th>
          <th>${item.fields.item_price}</th>
          <th>${item.fields.description}</th>
        </tr>` 
        })
        
        document.getElementById("table").innerHTML = htmlString
  }

  function addWishlist() {
    fetch("{% url 'wishlist:add_wishlist_item' %}", {
          method: "POST",
          body: new FormData(document.querySelector('#form'))
      }).then(refreshWishlist)
    return false
  }

  document.getElementById("button").onclick = addWishlist
  refreshWishlist()
</script>

{% endblock content %}